### PR TITLE
Compatibility with 'migrationNamespaces'

### PR DESCRIPTION
**Pull request by rapita**
This feature appears in yii2 version 2.0.10.

### CODE REVIEW

**Comment by Nemmo** [comment]
Ok, thank you very much for PR. But could you please explain how this feauture can be used? I dont understand you.

**Comment by rapita** [comment]
The feature allows you to automatically tracking migrations with namespace. It is much easier to automatically deploy project in production server.

For usage need add to console config file this code:
```
    'controllerMap' => [
        ...
        'migrate' => [
            'class' => 'yii\console\controllers\MigrateController',
            'migrationNamespaces' => [
                'nemmo\attachments\migrations',
            ],
        ],
        ...
    ],
```

**Comment by Nemmo** [comment]
Simple and perfect! (:

**Comment by rapita** [comment]
Thank you :)

**Pull request merged**
